# Generated by Django 5.0.1 on 2024-01-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0009_alter_todo_approaching_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='approaching_date',
            field=models.CharField(default='None', max_length=40, null=True),
        ),
    ]
